export const MAX_WEED_SPREAD_PERCENTAGE = 0.5;
export const WEED_WATER_DRAIN_SPEED = 7;
export const WEED_WATER_DRAIN_SPEED_WITH_ABSORPTION = 30;

export const MIOSN_EATER_MAX_MIOSN_EATEN = 3;

export const VORACIOUS_THORNS_KILL_CHANCE = 0.06;

export const FLOODVINE_FLOOD_CHANCE = 0.04;

export const PLANT_WATER_CONSUMPTION_SPEED = 5;
export const PLANT_FORCED_WATER_CONSUMPTION_SPEED = 15;
export const PLANT_TIME_WITHOUT_MIOSN = 12;
export const PLANT_YOUNGNESS_UPPER_BOUND = 5;

export const POSEIDON_FLOWER_FLOOD_SPEED = 15;

export const BASE_GROUND_WATER_LEVEL = 75;
export const GROUND_WATER_LEVEL_INCREASE = 6;
export const GROUND_WATER_LEVEL_INCREASE_CHANCE = 0.38;
